import { WrenchScrewdriverIcon } from '@heroicons/react/24/solid'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navigation from '../../components/navigation'


export default function PlayerHome() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation tab = "play" />
      <div className="grid place-items-center justify-center align-middle mt-16">
        <div className='justify-center'>
          <WrenchScrewdriverIcon className='h-24 w-24'/>
          <h1 className='font-bold text-4xl '>This portion of the website is currently under construction.</h1>
          <h1 className='text-xl '>Planned Content: Tournament Signup, Rating Statistics, Charity Events Advertising</h1>
        
        </div>
      </div>
    </div>
  )
}
